In [54]:
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

In [55]:
import seaborn as sns

In [56]:
import pandas as pd
df=pd.read_csv("hd1.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [86]:
X = df[['age', 'sex', 'cp', 'chol', 'restecg', 'ca', 'thal', 'slope']]
y = df['target']
X

age  sex  cp  chol  restecg  ca  thal  slope
0      52    1   0   212        1   2     3      2
1      53    1   0   203        0   0     3      0
2      70    1   0   174        1   0     3      0
3      61    1   0   203        1   1     3      2
4      62    0   0   294        1   3     2      1
...   ...  ...  ..   ...      ...  ..   ...    ...
3144   58    0   3   283        0   2     1      1
3145   52    0   2   306        0   2     0      1
3146   63    0   2   206        1   1     1      0
3147   55    0   0   186        0   1     2      1
3148   76    1   2   154        0   1     2      0

[3149 rows x 8 columns]

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [89]:
## Pieplining
numeric_preprocessor = Pipeline(
    steps=[
        ("imputation_mean", SimpleImputer(missing_values=np.nan, strategy="mean")),
        ("scaler", StandardScaler()),
    ]
)

In [90]:
from sklearn import set_config

In [91]:
set_config(display='diagram')

In [92]:
numeric_preprocessor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [93]:
categorical_preprocessor = Pipeline(
    steps=[
        (
            "imputation_constant",
            SimpleImputer(fill_value="missing", strategy="constant"),
        ),
        ("onehot", OneHotEncoder(handle_unknown="ignore")),
    ]
)

In [94]:
from sklearn.compose import ColumnTransformer

In [95]:
preprocessor=ColumnTransformer([
    ("numerical",numeric_preprocessor,["age","cp"])]


)

# preprocessor=ColumnTransformer(
#     [("categorical",categorical_preprocessor,["sex"]),
#     ("numerical",numeric_preprocessor,["age","cp"])]


# )   #here we dont want this 

In [96]:
#2 ways for creating pipeline
#1way
# from sklearn.pipeline import make_pipeline
# pipe1=make_pipeline(preprocessor,RandomForestRegressor())
#2way
steps=[("preprocessor",preprocessor),("Model",RandomForestRegressor())]
pipe1=Pipeline(steps)

In [97]:
pipe1

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'cp'])])),
                ('Model', RandomForestRegressor())])

In [98]:
pipe1.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'cp'])])),
                ('Model', RandomForestRegressor())])

In [99]:
y_pred=pipe1.predict(X_test)

In [103]:
import numpy as np
y_pred=np.round(y_pred)
y_pred

array([1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 0., 0., 0.

In [111]:
#hyperparameter tuning
param_grid={
    "Model__n_estimators":[1,10,20],
    "Model__max_features":["auto"],
}

In [112]:
grid_search=GridSearchCV(pipe1,param_grid=param_grid)
grid_search

GridSearchCV(estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('numerical',
                                                                         Pipeline(steps=[('imputation_mean',
                                                                                          SimpleImputer()),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['age',
                                                                          'cp'])])),
                                       ('Model', RandomForestRegressor())]),
             param_grid={'Model__max_features': ['auto'],
                         'Model__n_estimators': [1, 10, 20]})

In [113]:
grid_search.fit(X_train,y_train)

GridSearchCV(estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('numerical',
                                                                         Pipeline(steps=[('imputation_mean',
                                                                                          SimpleImputer()),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['age',
                                                                          'cp'])])),
                                       ('Model', RandomForestRegressor())]),
             param_grid={'Model__max_features': ['auto'],
                         'Model__n_estimators': [1, 10, 20]})

In [114]:
y_pred=grid_search.predict(X_test)

In [115]:
y_pred

array([0.9201434 , 0.4837013 , 0.50931754, 0.71334491, 0.18329935,
       0.61497321, 0.5682018 , 0.59864593, 0.52416126, 0.59537632,
       0.89948413, 0.20515931, 0.37477127, 0.31825388, 0.63028959,
       0.48152778, 0.61497321, 0.62080493, 0.54583544, 0.81      ,
       0.37290581, 0.75342357, 1.        , 0.55579343, 0.38984361,
       0.63028959, 0.66531593, 0.52356107, 0.52356107, 0.52416126,
       0.31209138, 0.67772595, 0.60742405, 0.60448616, 0.68462719,
       0.16453102, 0.89948413, 0.18329935, 0.40558622, 0.53154762,
       0.40558622, 0.9201434 , 0.55067641, 0.24808162, 0.18329935,
       0.76959049, 0.55111846, 0.53154762, 0.0841603 , 0.42578283,
       0.6841513 , 0.42578283, 0.62265076, 0.60742405, 0.1609367 ,
       0.32387779, 0.47391331, 0.30579505, 0.11952907, 0.63582799,
       0.6841513 , 0.62599815, 0.55642876, 0.18329935, 0.62080493,
       0.58027104, 0.45846829, 0.41429418, 0.32159407, 0.28866046,
       0.33044253, 0.31955544, 0.9875    , 0.49484457, 0.25685

In [116]:
y_pred=np.round(y_pred)
y_pred

array([1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1.,
       0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 0., 0., 0.

In [118]:
grid_search.best_params_

{'Model__max_features': 'auto', 'Model__n_estimators': 20}

In [121]:
steps=[("preprocessor",preprocessor),("Model",RandomForestRegressor(max_features='auto',n_estimators=20))]
pipe2=Pipeline(steps)

In [122]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'cp'])])),
                ('Model', RandomForestRegressor(n_estimators=20))])

In [124]:
y_pred=pipe2.predict(X_test)

In [125]:
y_pred

array([0.93320654, 0.52800283, 0.54377513, 0.66434898, 0.22129234,
       0.64011198, 0.49028011, 0.66413761, 0.51317328, 0.61383545,
       0.87602966, 0.23647831, 0.31394937, 0.30726562, 0.636617  ,
       0.41584235, 0.64011198, 0.65225967, 0.53988815, 0.72488095,
       0.35343358, 0.76152414, 1.        , 0.52569742, 0.36399946,
       0.636617  , 0.66954365, 0.45578474, 0.45578474, 0.51317328,
       0.38018849, 0.67116842, 0.53321972, 0.57698571, 0.69426351,
       0.20015873, 0.87602966, 0.22129234, 0.31290404, 0.48078838,
       0.31290404, 0.93320654, 0.65986701, 0.23537426, 0.22129234,
       0.78178562, 0.48152553, 0.48078838, 0.09813425, 0.5372619 ,
       0.68746151, 0.5372619 , 0.60407796, 0.53321972, 0.09556292,
       0.41572552, 0.63221817, 0.32550684, 0.10579511, 0.61873165,
       0.68746151, 0.69373046, 0.53366683, 0.22129234, 0.65225967,
       0.54766237, 0.40062006, 0.42053271, 0.24204313, 0.25465263,
       0.3453542 , 0.29691558, 1.        , 0.55611321, 0.27547